(function(){
  'use strict';
  var devices=[],statusMap={},selected={},selectedBackups={},commandTargets=[],importRows=[],adminState={configured:false,admin:false},pendingChange=null;
  var pages={dashboard:['运行概览','掌握设备与服务状态'],devices:['设备管理','在只读安全模式下巡检和查询交换机'],backups:['配置备份','查看和下载历史配置文件'],audit:['操作日志','追踪检测、查询及备份操作']};
  function qs(s){return document.querySelector(s)} function qsa(s){return document.querySelectorAll(s)}
  function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
  function toast(msg,error){var el=document.createElement('div');el.className='toast-item'+(error?' error':'');el.textContent=msg;qs('#toast').appendChild(el);setTimeout(function(){el.parentNode&&el.parentNode.removeChild(el)},4000)}
  function api(url,opts){opts=opts||{};opts.headers=opts.headers||{};if(opts.body)opts.headers['Content-Type']='application/json';return fetch(url,opts).then(function(r){if(r.status===204)return null;return r.json().then(function(j){if(!r.ok)throw new Error(j.error||'请求失败');return j})})}
  function gotoPage(name){qsa('.page').forEach(function(e){e.classList.remove('active')});qsa('.nav').forEach(function(e){e.classList.toggle('active',e.getAttribute('data-page')===name)});qs('#page-'+name).classList.add('active');qs('#page-title').textContent=pages[name][0];qs('#page-subtitle').textContent=pages[name][1];qs('#header-add').style.display=(name==='dashboard'||name==='devices')?'':'none';if(name==='backups')loadBackups();if(name==='audit')loadAudit()}
  qsa('.nav').forEach(function(b){b.onclick=function(){gotoPage(b.getAttribute('data-page'))}});qsa('[data-goto]').forEach(function(b){b.onclick=function(){gotoPage(b.getAttribute('data-goto'))}});
  function load(){return Promise.all([api('/api/devices'),api('/api/dashboard'),api('/api/admin/status')]).then(function(x){devices=x[0];adminState=x[2];updateAdminUI();renderDevices();var m=x[1];['total','huawei','h3c','snmp'].forEach(function(k){qs('#m-'+k).textContent=m[k]});qs('#dashboard-count').textContent=m.total+' 台';renderDashboard()}).catch(function(e){toast(e.message,true)})}
  function statusHTML(d){var s=statusMap[d.id];if(!s)return '<span class="status-dot"></span>未巡检';if(s.scanning)return '<span class="status-dot scanning"></span>巡检中';var on=s.ping||s.ssh;return '<span class="status-dot '+(on?'online':'offline')+'"></span>'+(on?'在线':'离线')+'<div class="sub">Ping '+(s.ping?'✓':'×')+' · SSH '+(s.ssh?'✓':'×')+(s.snmp==null?'':' · SNMP '+(s.snmp?'✓':'×'))+'</div>'}
  function deviceRows(items,compact){if(!items.length)return '<div class="empty"><strong>还没有设备</strong>点击“添加设备”录入第一台交换机</div>';var s='<table><thead><tr>'+(compact?'':'<th class="check-cell"><input type="checkbox" id="select-all"></th>')+'<th>设备</th><th>管理地址</th><th>状态</th><th>厂商</th><th>位置</th><th>操作</th></tr></thead><tbody>';items.forEach(function(d){var changeButton=adminState.admin?'<button class="icon-btn change-btn" data-action="change" data-id="'+d.id+'">变更</button>':'';var manageButtons=(!adminState.configured||adminState.admin)?'<button class="icon-btn" data-action="edit" data-id="'+d.id+'">编辑</button><button class="icon-btn" data-action="delete" data-id="'+d.id+'">删除</button>':'';s+='<tr>'+(compact?'':'<td class="check-cell"><input class="device-check" type="checkbox" data-id="'+d.id+'" '+(selected[d.id]?'checked':'')+'></td>')+'<td><div class="device-name">'+esc(d.name)+'</div><div class="sub">'+esc(d.model||'未填写型号')+'</div></td><td><b>'+esc(d.host)+'</b><div class="sub">SSH : '+d.sshPort+'</div></td><td>'+statusHTML(d)+'</td><td><span class="vendor '+d.vendor+'">'+d.vendor+'</span></td><td>'+esc(d.location||'—')+'</td><td class="row-actions"><button class="icon-btn" data-action="test" data-id="'+d.id+'">检测</button><button class="icon-btn" data-action="command" data-id="'+d.id+'">查询</button><button class="icon-btn" data-action="backup" data-id="'+d.id+'">备份</button>'+changeButton+(compact?'':manageButtons)+'</td></tr>'});return s+'</tbody></table>'}
  function renderDashboard(){qs('#dashboard-devices').innerHTML=deviceRows(devices.slice(0,6),true);bindActions(qs('#dashboard-devices'))}
  function filteredDevices(){var term=(qs('#search').value||'').toLowerCase(),vendor=qs('#vendor-filter').value;return devices.filter(function(d){return(!vendor||d.vendor===vendor)&&(!term||[d.name,d.host,d.location,d.model].join(' ').toLowerCase().indexOf(term)>=0)})}
  function renderDevices(){var list=filteredDevices();qs('#device-table').innerHTML=deviceRows(list,false);bindActions(qs('#device-table'));var all=qs('#select-all');if(all)all.onchange=function(){list.forEach(function(d){selected[d.id]=all.checked});renderDevices()};qsa('.device-check').forEach(function(c){c.onchange=function(){selected[c.getAttribute('data-id')]=c.checked}})}
  qs('#search').oninput=renderDevices;qs('#vendor-filter').onchange=renderDevices;
  function find(id){for(var i=0;i<devices.length;i++)if(devices[i].id===id)return devices[i]}
  function bindActions(root){root.querySelectorAll('[data-action]').forEach(function(b){b.onclick=function(){action(b.getAttribute('data-action'),find(b.getAttribute('data-id')))}})}
  function showTest(d,r){statusMap[d.id]={ping:r.ping.ok,ssh:r.ssh.ok,snmp:r.snmp?r.snmp.ok:null};renderDevices();renderDashboard();var parts=['Ping：'+r.ping.message,'SSH：'+r.ssh.message];if(r.snmp)parts.push('SNMP：'+r.snmp.message+(r.snmp.info&&r.snmp.info.sysName?'（'+r.snmp.info.sysName+'）':''));alert(d.name+' 检测结果\n\n'+parts.join('\n'))}
  function action(a,d){if(a==='edit')return openForm(d);if(a==='change')return openChange(d);if(a==='delete'){if(confirm('确定删除设备“'+d.name+'”？\n已有配置备份不会删除。'))api('/api/devices/'+d.id,{method:'DELETE'}).then(function(){toast('设备已删除');load()}).catch(function(e){toast(e.message,true)});return}if(a==='test'){statusMap[d.id]={scanning:true};renderDevices();renderDashboard();toast('正在检测 '+d.name+'…');api('/api/devices/'+d.id+'/test',{method:'POST'}).then(function(r){showTest(d,r)}).catch(function(e){delete statusMap[d.id];renderDevices();toast(e.message,true)});return}if(a==='command')return openCommand([d]);if(a==='backup'){toast('正在备份 '+d.name+'…');api('/api/devices/'+d.id+'/backup',{method:'POST'}).then(function(r){toast('备份完成：'+r.filename)}).catch(function(e){toast(e.message,true)})}}
  function openForm(d){qs('#device-form').reset();qs('#f-port').value=22;qs('#f-snmp-port').value=161;qs('#f-snmp').checked=true;qs('#f-id').value=d?d.id:'';qs('#form-title').textContent=d?'编辑设备':'添加设备';qs('#password-hint').textContent=d?'留空则保持原密码':'*';qs('#community-hint').textContent=d?'留空则保持原团体字':'*';if(d){qs('#f-name').value=d.name;qs('#f-host').value=d.host;qs('#f-vendor').value=d.vendor;qs('#f-model').value=d.model||'';qs('#f-location').value=d.location||'';qs('#f-port').value=d.sshPort;qs('#f-user').value=d.username;qs('#f-snmp').checked=d.snmpEnabled;qs('#f-snmp-port').value=d.snmpPort}qs('#device-modal').classList.add('open')}
  qs('#header-add').onclick=function(){if(adminState.configured&&!adminState.admin){toast('添加设备需要管理员权限',true);openAdmin();return}openForm(null)};qsa('[data-close]').forEach(function(b){b.onclick=function(){b.closest('.modal').classList.remove('open')}});qsa('.modal').forEach(function(m){m.onclick=function(e){if(e.target===m)m.classList.remove('open')}});
  qs('#device-form').onsubmit=function(e){e.preventDefault();var id=qs('#f-id').value,body={name:qs('#f-name').value,host:qs('#f-host').value,vendor:qs('#f-vendor').value,model:qs('#f-model').value,location:qs('#f-location').value,sshPort:Number(qs('#f-port').value),username:qs('#f-user').value,password:qs('#f-password').value,snmpEnabled:qs('#f-snmp').checked,snmpPort:Number(qs('#f-snmp-port').value),community:qs('#f-community').value};var btn=qs('#save-device');btn.disabled=true;btn.textContent='保存中…';api('/api/devices'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(body)}).then(function(){qs('#device-modal').classList.remove('open');toast(id?'设备已更新':'设备已添加');load()}).catch(function(x){toast(x.message,true)}).then(function(){btn.disabled=false;btn.textContent='保存设备'})};
  function openCommand(targets){commandTargets=targets;qs('#command-id').value=targets.map(function(d){return d.id}).join(',');qs('#command-title').textContent=targets.length===1?'查询 '+targets[0].name:'批量查询 '+targets.length+' 台设备';qs('#command-preset').value='';qs('#command-input').value='display interface brief';qs('#command-output').classList.add('hidden');qs('#command-output').textContent='';qs('#command-modal').classList.add('open')}
  qs('#command-preset').onchange=function(){if(this.value)qs('#command-input').value=this.value};
  qs('#batch-command').onclick=function(){var list=devices.filter(function(d){return selected[d.id]});if(!list.length){toast('请先勾选要操作的设备',true);return}openCommand(list)};
  qs('#command-form').onsubmit=function(e){e.preventDefault();var out=qs('#command-output'),cmd=qs('#command-input').value;out.classList.remove('hidden');out.textContent='正在连接并查询，请稍候…';if(commandTargets.length===1){api('/api/devices/'+commandTargets[0].id+'/command',{method:'POST',body:JSON.stringify({command:cmd})}).then(function(r){out.textContent=r.output||'查询已完成，无返回内容'}).catch(function(x){out.textContent='错误：'+x.message})}else{api('/api/batch-command',{method:'POST',body:JSON.stringify({ids:commandTargets.map(function(d){return d.id}),command:cmd})}).then(function(items){out.textContent=items.map(function(x){return '===== '+x.name+' =====\n'+(x.success?(x.output||'查询成功，无返回内容'):'错误：'+x.error)}).join('\n\n')}).catch(function(x){out.textContent='错误：'+x.message})}};
  qs('#scan-all').onclick=function(){if(!devices.length){toast('还没有设备',true);return}devices.forEach(function(d){statusMap[d.id]={scanning:true}});renderDevices();renderDashboard();var btn=qs('#scan-all');btn.disabled=true;btn.textContent='巡检中…';api('/api/scan',{method:'POST'}).then(function(items){var online=0;items.forEach(function(x){statusMap[x.id]=x;if(x.ping||x.ssh)online++});renderDevices();renderDashboard();toast('巡检完成：在线 '+online+' / '+items.length)}).catch(function(e){toast(e.message,true)}).then(function(){btn.disabled=false;btn.textContent='巡检全部'})};
  function loadBackups(){api('/api/backups').then(function(items){if(!items.length){qs('#backup-table').innerHTML='<div class="empty"><strong>暂无配置备份</strong>在设备列表中点击“备份”即可创建</div>';return}var s='<table><thead><tr><th class="check-cell"></th><th>文件名</th><th>大小</th><th>备份时间</th><th>操作</th></tr></thead><tbody>';items.forEach(function(x){s+='<tr><td class="check-cell"><input class="backup-check" type="checkbox" data-name="'+esc(x.name)+'" '+(selectedBackups[x.name]?'checked':'')+'></td><td><b>'+esc(x.name)+'</b></td><td>'+Math.max(1,Math.round(x.size/1024))+' KB</td><td>'+new Date(x.modified).toLocaleString()+'</td><td><button class="icon-btn view-backup" data-name="'+esc(x.name)+'">查看</button><a class="icon-btn" href="/api/backups/'+encodeURIComponent(x.name)+'">下载</a></td></tr>'});qs('#backup-table').innerHTML=s+'</tbody></table>';qsa('.view-backup').forEach(function(b){b.onclick=function(){viewBackup(b.getAttribute('data-name'))}});qsa('.backup-check').forEach(function(c){c.onchange=function(){var name=c.getAttribute('data-name');if(c.checked){var chosen=Object.keys(selectedBackups).filter(function(k){return selectedBackups[k]});if(chosen.length>=2){c.checked=false;toast('配置对比最多选择两个文件',true);return}selectedBackups[name]=true}else delete selectedBackups[name]}})}).catch(function(e){toast(e.message,true)})}
  function viewBackup(name){qs('#viewer-title').textContent=name;qs('#viewer-content').textContent='正在读取…';qs('#viewer-modal').classList.add('open');api('/api/backups/'+encodeURIComponent(name)+'?view=1').then(function(x){qs('#viewer-content').textContent=x.content}).catch(function(e){qs('#viewer-content').textContent='读取失败：'+e.message})}
  qs('#compare-backups').onclick=function(){var names=Object.keys(selectedBackups).filter(function(k){return selectedBackups[k]});if(names.length!==2){toast('请勾选两份配置备份进行对比',true);return}qs('#compare-left-title').textContent=names[0];qs('#compare-right-title').textContent=names[1];qs('#compare-left').textContent='正在读取…';qs('#compare-right').textContent='正在读取…';qs('#compare-modal').classList.add('open');Promise.all(names.map(function(name){return api('/api/backups/'+encodeURIComponent(name)+'?view=1')})).then(function(x){qs('#compare-left').textContent=x[0].content;qs('#compare-right').textContent=x[1].content}).catch(function(e){toast(e.message,true)})};
  qs('#backup-all').onclick=function(){if(!devices.length){toast('还没有设备',true);return}if(!confirm('将依次备份全部 '+devices.length+' 台设备，是否继续？'))return;var btn=qs('#backup-all');btn.disabled=true;btn.textContent='备份中…';api('/api/backup-all',{method:'POST'}).then(function(items){var ok=items.filter(function(x){return x.success}).length;toast('批量备份完成：成功 '+ok+'，失败 '+(items.length-ok),ok!==items.length);loadBackups()}).catch(function(e){toast(e.message,true)}).then(function(){btn.disabled=false;btn.textContent='备份全部'})};
  function loadAudit(){api('/api/logs').then(function(items){if(!items.length){qs('#audit-table').innerHTML='<div class="empty"><strong>暂无操作日志</strong>执行检测、命令或备份后会自动记录</div>';return}var s='<table><thead><tr><th>时间</th><th>操作</th><th>设备</th><th>结果</th><th>详情</th></tr></thead><tbody>';items.forEach(function(x){s+='<tr><td>'+new Date(x.time).toLocaleString()+'</td><td><b>'+esc(x.action)+'</b></td><td>'+esc(x.deviceName||'全部设备')+'</td><td class="'+(x.success?'result-ok':'result-fail')+'">'+(x.success?'成功':'失败')+'</td><td class="audit-detail" title="'+esc(x.detail)+'">'+esc(x.detail)+'</td></tr>'});qs('#audit-table').innerHTML=s+'</tbody></table>'}).catch(function(e){toast(e.message,true)})}
  function updateAdminUI(){var b=qs('#admin-toggle');if(adminState.admin){b.textContent='◆ 管理员已解锁';b.classList.add('admin-active');b.title='点击立即锁定管理员权限'}else{b.textContent='◆ 只读安全模式';b.classList.remove('admin-active');b.title='点击解锁管理员权限'}}
  function openAdmin(){qs('#admin-form').reset();qs('#admin-title').textContent=adminState.configured?'解锁管理员权限':'首次设置管理员密码';qs('#admin-subtitle').textContent=adminState.configured?'管理员会话默认保持 15 分钟':'设置后才能执行受控配置变更';qs('#admin-submit').textContent=adminState.configured?'解锁':'设置并解锁';qs('#admin-password').setAttribute('autocomplete',adminState.configured?'current-password':'new-password');qs('#admin-modal').classList.add('open');setTimeout(function(){qs('#admin-password').focus()},50)}
  qs('#admin-toggle').onclick=function(){if(adminState.admin){if(!confirm('确定立即锁定管理员权限？\n只读查询不受影响。'))return;api('/api/admin/logout',{method:'POST'}).then(function(){adminState.admin=false;updateAdminUI();renderDevices();renderDashboard();toast('管理员权限已锁定')}).catch(function(e){toast(e.message,true)})}else openAdmin()};
  qs('#admin-form').onsubmit=function(e){e.preventDefault();var btn=qs('#admin-submit'),endpoint=adminState.configured?'/api/admin/login':'/api/admin/setup';btn.disabled=true;btn.textContent='验证中…';api(endpoint,{method:'POST',body:JSON.stringify({password:qs('#admin-password').value})}).then(function(){adminState.configured=true;adminState.admin=true;qs('#admin-modal').classList.remove('open');updateAdminUI();renderDevices();renderDashboard();toast('管理员权限已解锁');if(pendingChange){var d=pendingChange;pendingChange=null;openChange(d)}}).catch(function(x){toast(x.message,true)}).then(function(){btn.disabled=false;btn.textContent=adminState.configured?'解锁':'设置并解锁'})};
  function openChange(d){if(!adminState.admin){pendingChange=d;openAdmin();return}qs('#change-id').value=d.id;qs('#change-title').textContent='变更 '+d.name;qs('#confirm-device-label').textContent=d.name;qs('#confirm-device').value='';qs('#change-script').value='system-view\ninterface GigabitEthernet1/0/1\ndescription Uplink';qs('#change-output').classList.add('hidden');qs('#change-output').textContent='';qs('#change-modal').classList.add('open')}
  qs('#change-form').onsubmit=function(e){e.preventDefault();var id=qs('#change-id').value,out=qs('#change-output'),btn=qs('#change-submit');out.classList.remove('hidden');out.textContent='正在验证并执行变更前备份，请勿关闭程序…';btn.disabled=true;api('/api/devices/'+id+'/change',{method:'POST',body:JSON.stringify({script:qs('#change-script').value,confirmDevice:qs('#confirm-device').value})}).then(function(r){out.textContent='变更前备份：'+r.backup+'\n\n'+r.warning+'\n\n===== 设备返回 =====\n'+(r.output||'设备未返回文本，请立即使用只读查询核查。');toast('配置变更会话已完成，请立即核查设备')}).catch(function(x){out.textContent='错误：'+x.message;if(x.message.indexOf('管理员权限')>=0){adminState.admin=false;updateAdminUI();renderDevices()}toast(x.message,true)}).then(function(){btn.disabled=false})};
  function parseCSV(text){var rows=[],row=[],cell='',quoted=false;for(var i=0;i<text.length;i++){var ch=text.charAt(i);if(quoted){if(ch==='"'&&text.charAt(i+1)==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(ch!=='\r')cell+=ch}if(cell!==''||row.length){row.push(cell);rows.push(row)}if(quoted)throw new Error('CSV 引号未闭合');return rows}
  function csvToDevices(text){var rows=parseCSV(text.replace(/^\uFEFF/,''));if(rows.length<2)throw new Error('CSV 中没有设备数据');var headers=rows[0].map(function(x){return x.trim().toLowerCase()}),required=['name','host','vendor','username','password'];required.forEach(function(k){if(headers.indexOf(k)<0)throw new Error('缺少必填列：'+k)});function value(row,key){var i=headers.indexOf(key);return i<0?'':(row[i]||'').trim()}var out=[];for(var n=1;n<rows.length;n++){var row=rows[n];if(row.join('').trim()==='')continue;var vendor=value(row,'vendor').toLowerCase();vendor=vendor==='huawei'?'Huawei':vendor==='h3c'?'H3C':value(row,'vendor');var snmp=value(row,'snmpenabled').toLowerCase();out.push({name:value(row,'name'),host:value(row,'host'),vendor:vendor,model:value(row,'model'),location:value(row,'location'),sshPort:Number(value(row,'sshport')||22),username:value(row,'username'),password:value(row,'password'),snmpEnabled:['true','1','yes','y','是'].indexOf(snmp)>=0,snmpPort:Number(value(row,'snmpport')||161),community:value(row,'community')})}if(!out.length)throw new Error('CSV 中没有设备数据');if(out.length>1000)throw new Error('一次最多导入 1000 台设备');return out}
  function renderImportPreview(){var s='<div class="preview-head">已读取 <b>'+importRows.length+'</b> 台设备，仅预览前 8 行</div><table><thead><tr><th>名称</th><th>管理地址</th><th>厂商</th><th>SSH 用户</th><th>SNMP</th></tr></thead><tbody>';importRows.slice(0,8).forEach(function(d){s+='<tr><td>'+esc(d.name)+'</td><td>'+esc(d.host)+'</td><td>'+esc(d.vendor)+'</td><td>'+esc(d.username)+'</td><td>'+(d.snmpEnabled?'启用':'关闭')+'</td></tr>'});qs('#import-preview').innerHTML=s+'</tbody></table>';qs('#import-submit').disabled=false}
  qs('#import-open').onclick=function(){if(adminState.configured&&!adminState.admin){toast('批量导入需要管理员权限',true);openAdmin();return}importRows=[];qs('#import-form').reset();qs('#import-submit').disabled=true;qs('#import-preview').innerHTML='<div class="empty-mini">尚未选择文件</div>';qs('#import-modal').classList.add('open')};
  qs('#import-file').onchange=function(){var file=this.files&&this.files[0];if(!file)return;if(file.size>2*1024*1024){toast('CSV 文件不能超过 2 MB',true);this.value='';return}var reader=new FileReader();reader.onload=function(e){try{var bytes=new Uint8Array(e.target.result),text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch(ignore){text=new TextDecoder('gbk').decode(bytes)}importRows=csvToDevices(text);renderImportPreview()}catch(err){importRows=[];qs('#import-submit').disabled=true;qs('#import-preview').innerHTML='<div class="empty-mini error-text">'+esc(err.message)+'</div>';toast(err.message,true)}};reader.onerror=function(){toast('无法读取 CSV 文件',true)};reader.readAsArrayBuffer(file)};
  qs('#import-form').onsubmit=function(e){e.preventDefault();if(!importRows.length)return;var btn=qs('#import-submit');btn.disabled=true;btn.textContent='导入中…';api('/api/import/devices',{method:'POST',body:JSON.stringify({devices:importRows})}).then(function(r){qs('#import-modal').classList.remove('open');toast('成功导入 '+r.imported+' 台设备');importRows=[];load()}).catch(function(x){toast(x.message,true)}).then(function(){btn.disabled=false;btn.textContent='确认导入'})};
  qs('#refresh-backups').onclick=loadBackups;qs('#refresh-audit').onclick=loadAudit;load();
})();
